inherit_from: configs/pointcloud_crop/test_optim/room_grid64_matterport.yaml
data:
  input_type: pointcloud_crop
  classes: ['']
  path: data/demo/Matterport3D_processed
  pointcloud_n: 65536
  pointcloud_noise: 0.0
  points_subsample: 65536 
  points_file: points_iou.npz
  points_iou_file: points_iou.npz
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  voxels_file: null
  multi_files: null
  unit_size: 0.002 # define the size of a voxel, in meter
  query_vol_size: 25 # query crop in voxel
training:
  out_dir: out/demo_matterport
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud_crop/room_grid64.pt