method: conv_onet
data:
  input_type: pointcloud
  classes: null
  path: data/ShapeNet
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  voxels_file: null
model:
  encoder: pointnet_plus_plus
  decoder: simple_local_point
  decoder_kwargs:
    hidden_size: 32
    sample_mode: gaussian
    gaussian_val: 0.2
  c_dim: 32
training:
  out_dir: out/pointcloud/shapenet_pointconv
  batch_size: 24
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
