inherit_from: configs/voxel/shapenet_1plane.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/voxel/voxel_shapenet_1plane.pt
